services:
  test-frontend-7:
    build:
      context: .
      target: production
    image: test-frontend-7
    container_name: test-frontend-7
    environment:
      APPINSIGHTS_CLOUDROLE: test-frontend-7-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
