# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  test-frontend-7:
    build:
      target: development
    image: test-frontend-7-development
    container_name: test-frontend-7-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
