apiVersion: v2
description: A Helm Chart to deploy the test-frontend-7 application to Kubernetes
name: test-frontend-7
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: adp-helm-library
  version: ^1.0.0
  repository: https://raw.githubusercontent.com/defra/adp-helm-repository/main/adp-helm-library
