{{- include "adp-helm-library.deployment" (list . "test-frontend-7.deployment") -}}
{{- define "test-frontend-7.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "test-frontend-7.container") }}
{{- end -}}
